### ISSUE TITLE
[BUG REPORT] Yuki-chan "-playing" command doesn't work properly

### ISSUE THREAD

**Issue by MTeycheney** [hsiw/WishBot#5]
Hello,

I'm sorry for disturbing you, but I contacting you to report a bug about the discord bot Yuki-chan.

I used to use the '-playing' command to know the current song name. But since yesterday, Yuki-chan is stuck with a song name: "Ebb and flow" by "Ray", and whatever the current song is, everytime I use "-playing", Yuki-chan will always tell me it's Ebb and flow by Ray.

Also, since approximatively 30 minutes, the -playing command doesn't work anymore.

I'm joining a screenshot to this ticket hoping this will help you.
![capture](https://cloud.githubusercontent.com/assets/24414345/20932575/5d5bf4f6-bbd5-11e6-8ef2-af082595bdd0.PNG)

I'm staying at your disposal if you need more informations.

Cordially

**Comment by hsiW** [comment]
Resolved
