### ISSUE TITLE
Can i host my own boss using wishbot resources? 

### ISSUE THREAD

**Issue by JillVa11a** [hsiw/WishBot#6]

**Comment by dddlr** [comment]
Uh... I don't follow. If you meant hosting Wishbot from your own computer, you can. However, note that since no support will be given for this source code, you're on your own.

**Comment by dddlr** [comment]
Though I'll give you a few pointers (I'm going from memory here): you'll need to 

- set up `mariadb`, in order for the database to work

- perform `npm install` in the bot's directory

- rename all the files ending in `-blank` so they don't end in `-blank` and fill them in, *especially* `options.json`.
